from django.urls import path

from .api import (
    admin_user_detail,
    admin_users,
    auth_delete,
    auth_login,
    auth_logout,
    auth_me,
    auth_register,
    exchange_connection_detail,
    exchange_connection_sync,
    exchange_connections,
    get_signal,
    import_binance_csv,
    live_price,
    portfolio_analytics,
    portfolio_asset_detail,
    portfolio_assets,
    portfolio_insights,
    portfolio_overview,
    portfolio_transaction_detail,
    portfolio_transactions,
    portfolio_transfer,
    security_change_password,
    security_two_factor,
    user_settings,
)

urlpatterns = [
    path("auth/register/", auth_register),
    path("auth/login/", auth_login),
    path("auth/logout/", auth_logout),
    path("auth/me/", auth_me),
    path("auth/delete/", auth_delete),
    path("admin/users/", admin_users),
    path("admin/users/<int:user_id>/", admin_user_detail),
    path("get-signal/<str:symbol>/", get_signal),
    path("portfolio/overview/", portfolio_overview),
    path("portfolio/analytics/", portfolio_analytics),
    path("portfolio/insights/", portfolio_insights),
    path("portfolio/transactions/", portfolio_transactions),
    path("portfolio/transactions/<int:transaction_id>/", portfolio_transaction_detail),
    path("portfolio/assets/", portfolio_assets),
    path("portfolio/assets/<int:holding_id>/", portfolio_asset_detail),
    path("portfolio/transfer/", portfolio_transfer),
    path("portfolio/import/csv/", import_binance_csv),
    path("portfolio/live-price/", live_price),
    path("settings/", user_settings),
    path("security/password/", security_change_password),
    path("security/two-factor/", security_two_factor),
    path("connections/", exchange_connections),
    path("connections/<int:connection_id>/", exchange_connection_detail),
    # Aliases so the frontend proxy routes (/api/exchange/...) resolve correctly
    path("exchange/connect/", exchange_connections),
    path("exchange/connections/", exchange_connections),
    path("exchange/connections/<int:connection_id>/", exchange_connection_detail),
    path("exchange/connections/<int:connection_id>/sync/", exchange_connection_sync),
]
