# Generated by Django 5.2.7 on 2026-03-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_type", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell"), ("transfer", "Transfer")], max_length=20)),
                ("quantity", models.FloatField()),
                ("price", models.FloatField()),
                ("total", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="portfolio.asset")),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="portfolio.portfolio")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
